#pragma once
#include <algorithm>
#include <cmath>

// Small reference core to merge into the C++ DSP kernel generated by Xcode.
// MIDI note handling/render event iteration should remain Apple's generated code.
struct SineVoice {
    double sampleRate = 48000.0;
    double phase = 0.0;
    int midiNote = 69;
    bool gate = false;
    float pitchSemitones = 0.0f;
    float volumeDB = -12.0f;

    void setNote(int note, bool on) noexcept {
        midiNote = std::clamp(note, 0, 127);
        gate = on;
    }

    void setPitch(float semitones) noexcept {
        pitchSemitones = std::clamp(semitones, -24.0f, 24.0f);
    }

    void setVolume(float dB) noexcept {
        volumeDB = std::clamp(dB, -60.0f, 0.0f);
    }

    float render() noexcept {
        if (!gate) return 0.0f;

        const double note = double(midiNote) + double(pitchSemitones);
        const double hz = 440.0 * std::exp2((note - 69.0) / 12.0);
        const double increment = hz / sampleRate;
        const float gain = std::pow(10.0f, volumeDB / 20.0f);
        const float y = std::sin(phase * 2.0 * M_PI) * gain;

        phase += increment;
        phase -= std::floor(phase);
        return y;
    }
};
