import AudioToolbox

// Merge these addresses/specs into the files generated by Xcode's
// current Audio Unit Extension App / Instrument template.

enum TemplateParameterAddress: AUParameterAddress {
    case pitch = 0
    case volume = 1
}

struct TemplateParameterSpec {
    static let pitchRange: ClosedRange<AUValue> = -24...24
    static let volumeRange: ClosedRange<AUValue> = -60...0
    static let defaultPitch: AUValue = 0
    static let defaultVolume: AUValue = -12
}
